### PR TITLE
Re-align dev / master

### PR DESCRIPTION
**Pull request by fabian-s**

### CODE REVIEW

**Comment by fabian-s** [comment]
@jeff-goldsmith @julia-wrobel 
this is long overdue, plz check it out and let me know if this works for you....

**Comment by fabian-s** [comment]
.. more precisely: one of you needs to approve so we can merge this back into master.

**Comment by fabian-s** [comment]
hmmm... these are both in "Suggests" already - are you sure you have them installed? always a good idea to copy paste the actual error message for this kind of thing for more streamlined communication

**Comment by julia-wrobel** [comment]
Yeah I installed the packages and it works for me now..  in the future I'll check that first and print the actually error. Everything looks good to me for merging.

**Pull request merged**
